name: main

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download latest bitsandbytes wheel
        uses: robinraju/release-downloader@v1
        with:
          repository: "bitsandbytes-foundation/bitsandbytes"
          tag: "continuous-release_main"
          fileName: "bitsandbytes*manylinux*x86_64.whl"

          tarBall: false
          zipBall: false

      - name: Install dependencies
        run: pip install pkginfo

      - name: Get package version
        shell: python
        run: |
          from pkginfo import Wheel
          from pathlib import Path
          from os import getenv

          wheel = Wheel(next(Path('.').rglob('bitsandbytes*manylinux*x86_64.whl')))

          env_file = getenv('GITHUB_ENV')
          with open(env_file, "a") as myfile:
              myfile.write(f"WHEEL_VERSION={wheel.version}")

      - name: Move and rename wheel
        run: |
          # remove old files
          rm -rf bitsandbytes/*

          find . -maxdepth 1 -type f -name 'bitsandbytes*manylinux*x86_64.whl' -print0 | while IFS= read -r -d '' wheel; do
            wheel_filename=$(basename "$wheel")

            # Strip off the original version
            rest=${wheel_filename#bitsandbytes-*-}
            new_name="bitsandbytes-${WHEEL_VERSION}-${rest}"

            echo "Renaming $wheel_filename → $new_name"
            mv "$wheel" "bitsandbytes/${new_name}"
          done

      - name: Generate directory listings
        run: python directory_listing.py

      - name: Generate permalinks
        run: python permalinks.py

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update bitsandbytes wheel to version ${WHEEL_VERSION}"
            git push
          fi

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
